import { FeatureFlagKey as F } from '@therapyos/types';

export const PLANS = [
  {
    code: 'STARTER',
    name: 'Starter',
    description: 'Single-branch essentials: CRM, appointments, walk-ins, billing and basic reports.',
    monthlyPrice: 999,
    annualPrice: 9990,
    maxBranches: 1,
    maxUsers: 5,
    maxCustomers: 2000,
    features: [F.PACKAGES_ENABLED],
    sortOrder: 1,
  },
  {
    code: 'GROWTH',
    name: 'Growth',
    description: 'Packages, memberships, WhatsApp, inventory and advanced analytics.',
    monthlyPrice: 1999,
    annualPrice: 19990,
    maxBranches: 1,
    maxUsers: 15,
    maxCustomers: 10000,
    features: [F.PACKAGES_ENABLED, F.MEMBERSHIP_ENABLED, F.WHATSAPP_ENABLED, F.INVENTORY_ENABLED, F.ADVANCED_ANALYTICS],
    sortOrder: 2,
  },
  {
    code: 'BUSINESS',
    name: 'Business',
    description: 'Multi-branch operations with staff commissions and retention automation.',
    monthlyPrice: 3999,
    annualPrice: 39990,
    maxBranches: 3,
    maxUsers: 50,
    maxCustomers: 50000,
    features: [
      F.PACKAGES_ENABLED,
      F.MEMBERSHIP_ENABLED,
      F.WHATSAPP_ENABLED,
      F.INVENTORY_ENABLED,
      F.ADVANCED_ANALYTICS,
      F.MULTI_BRANCH,
      F.COMMISSIONS,
      F.RETENTION_AUTOMATION,
    ],
    sortOrder: 3,
  },
  {
    code: 'ENTERPRISE',
    name: 'Enterprise',
    description: 'HQ dashboard, franchise, API, white-label, AI assistant and priority support.',
    monthlyPrice: 7999,
    annualPrice: 79990,
    maxBranches: 50,
    maxUsers: 1000,
    maxCustomers: 1000000,
    features: Object.values(F),
    sortOrder: 4,
  },
];

export const SYSTEM_TEMPLATES: Array<{ event: string; channel: 'WHATSAPP' | 'SMS' | 'EMAIL'; name: string; subject?: string; body: string }> = [
  {
    event: 'APPOINTMENT_BOOKED',
    channel: 'WHATSAPP',
    name: 'Appointment confirmation',
    body: 'Hi {{customer_name}}, your appointment at {{branch_name}} is confirmed for {{appointment_time}}.\nService: {{service_name}}',
  },
  {
    event: 'APPOINTMENT_BOOKED',
    channel: 'EMAIL',
    name: 'Appointment confirmation',
    subject: 'Your appointment at {{business_name}} is confirmed',
    body: '<p>Hi {{customer_name}},</p><p>Your appointment at <b>{{branch_name}}</b> is confirmed for <b>{{appointment_time}}</b>.</p><p>Service: {{service_name}}</p>',
  },
  {
    event: 'APPOINTMENT_REMINDER',
    channel: 'WHATSAPP',
    name: 'Appointment reminder',
    body: 'Reminder: {{customer_name}}, your {{service_name}} session at {{branch_name}} is on {{appointment_time}}. Reply to reschedule.',
  },
  {
    event: 'APPOINTMENT_CANCELLED',
    channel: 'WHATSAPP',
    name: 'Appointment cancelled',
    body: 'Hi {{customer_name}}, your appointment on {{appointment_time}} at {{branch_name}} has been cancelled.',
  },
  {
    event: 'SESSION_COMPLETED',
    channel: 'WHATSAPP',
    name: 'Thank you',
    body: 'Thank you for visiting {{branch_name}}, {{customer_name}}! We hope you enjoyed your {{service_name}}.',
  },
  {
    event: 'FEEDBACK_REQUEST',
    channel: 'WHATSAPP',
    name: 'Feedback request',
    body: 'Hi {{customer_name}}, how was your {{service_name}} today? Rate us here: {{feedback_link}}',
  },
  {
    event: 'PAYMENT_RECEIVED',
    channel: 'WHATSAPP',
    name: 'Payment receipt',
    body: 'Payment of {{amount}} received for invoice {{invoice_number}}. Thank you, {{customer_name}}!',
  },
  {
    event: 'PAYMENT_RECEIVED',
    channel: 'EMAIL',
    name: 'Payment receipt',
    subject: 'Receipt for invoice {{invoice_number}}',
    body: '<p>Hi {{customer_name}},</p><p>We received your payment of <b>{{amount}}</b> for invoice {{invoice_number}}.</p><p>Thank you for choosing {{business_name}}.</p>',
  },
  {
    event: 'PACKAGE_EXPIRING',
    channel: 'WHATSAPP',
    name: 'Package expiring',
    body: 'Hi {{customer_name}}, your package "{{package_name}}" expires on {{expiry_date}} with {{remaining_sessions}} session(s) left. Book now!',
  },
  {
    event: 'MEMBERSHIP_EXPIRING',
    channel: 'WHATSAPP',
    name: 'Membership expiring',
    body: 'Hi {{customer_name}}, your {{plan_name}} membership expires on {{expiry_date}}. Renew to keep your benefits.',
  },
  {
    event: 'BIRTHDAY',
    channel: 'WHATSAPP',
    name: 'Birthday wishes',
    body: 'Happy birthday {{customer_name}}! Treat yourself at {{business_name}} this month.',
  },
  {
    event: 'WIN_BACK',
    channel: 'WHATSAPP',
    name: 'We miss you',
    body: 'Hi {{customer_name}}, we miss you at {{business_name}}! It has been {{days_since_visit}} days since your last visit.',
  },
  {
    event: 'LOW_STOCK',
    channel: 'EMAIL',
    name: 'Low stock alert',
    subject: 'Low stock: {{product_name}} at {{branch_name}}',
    body: '<p>{{product_name}} is low at {{branch_name}}: {{quantity}} left (reorder level {{reorder_level}}).</p>',
  },
];
