import { LedgerAccountType } from '@prisma/client';

export const LEDGER = {
  CASH: '1000',
  BANK: '1010',
  UPI_CLEARING: '1020',
  CARD_CLEARING: '1030',
  GATEWAY_CLEARING: '1040',
  RECEIVABLES: '1100',
  INVENTORY: '1200',
  TAX_PAYABLE: '2000',
  DEFERRED_REVENUE: '2100',
  CUSTOMER_REFUNDS: '2200',
  SERVICE_REVENUE: '4000',
  PRODUCT_REVENUE: '4010',
  PACKAGE_REVENUE: '4020',
  MEMBERSHIP_REVENUE: '4030',
  DISCOUNTS: '4900',
  ROUNDING: '4950',
  SALES_RETURNS: '4990',
  COMMISSION_EXPENSE: '5000',
  COGS: '5100',
  OPERATING_EXPENSE: '5200',
} as const;

export const DEFAULT_LEDGER_ACCOUNTS: { code: string; name: string; type: LedgerAccountType }[] = [
  { code: LEDGER.CASH, name: 'Cash in hand', type: 'ASSET' },
  { code: LEDGER.BANK, name: 'Bank', type: 'ASSET' },
  { code: LEDGER.UPI_CLEARING, name: 'UPI clearing', type: 'ASSET' },
  { code: LEDGER.CARD_CLEARING, name: 'Card clearing', type: 'ASSET' },
  { code: LEDGER.GATEWAY_CLEARING, name: 'Payment gateway clearing', type: 'ASSET' },
  { code: LEDGER.RECEIVABLES, name: 'Accounts receivable', type: 'ASSET' },
  { code: LEDGER.INVENTORY, name: 'Inventory', type: 'ASSET' },
  { code: LEDGER.TAX_PAYABLE, name: 'Tax payable', type: 'LIABILITY' },
  { code: LEDGER.DEFERRED_REVENUE, name: 'Deferred revenue (packages/memberships)', type: 'LIABILITY' },
  { code: LEDGER.CUSTOMER_REFUNDS, name: 'Customer refunds payable', type: 'LIABILITY' },
  { code: LEDGER.SERVICE_REVENUE, name: 'Service revenue', type: 'INCOME' },
  { code: LEDGER.PRODUCT_REVENUE, name: 'Product revenue', type: 'INCOME' },
  { code: LEDGER.PACKAGE_REVENUE, name: 'Package revenue', type: 'INCOME' },
  { code: LEDGER.MEMBERSHIP_REVENUE, name: 'Membership revenue', type: 'INCOME' },
  { code: LEDGER.DISCOUNTS, name: 'Discounts given', type: 'INCOME' },
  { code: LEDGER.ROUNDING, name: 'Rounding', type: 'INCOME' },
  { code: LEDGER.SALES_RETURNS, name: 'Sales returns and refunds', type: 'INCOME' },
  { code: LEDGER.COMMISSION_EXPENSE, name: 'Therapist commission', type: 'EXPENSE' },
  { code: LEDGER.COGS, name: 'Cost of goods sold', type: 'EXPENSE' },
  { code: LEDGER.OPERATING_EXPENSE, name: 'Operating expenses', type: 'EXPENSE' },
];
