import { SystemRole } from './enums';

export const PERMISSIONS = {
  // tenant & setup
  TENANT_READ: 'tenant.read',
  TENANT_UPDATE: 'tenant.update',
  SETTINGS_MANAGE: 'settings.manage',
  BRANCH_READ: 'branch.read',
  BRANCH_MANAGE: 'branch.manage',
  USER_READ: 'user.read',
  USER_MANAGE: 'user.manage',
  ROLE_READ: 'role.read',
  ROLE_MANAGE: 'role.manage',
  AUDIT_READ: 'audit.read',
  // catalogue
  SERVICE_READ: 'service.read',
  SERVICE_MANAGE: 'service.manage',
  THERAPIST_READ: 'therapist.read',
  THERAPIST_MANAGE: 'therapist.manage',
  // customers
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  CUSTOMER_DELETE: 'customer.delete',
  CUSTOMER_CONTACT_VIEW: 'customer.contact.view',
  // operations
  APPOINTMENT_READ: 'appointment.read',
  APPOINTMENT_CREATE: 'appointment.create',
  APPOINTMENT_UPDATE: 'appointment.update',
  APPOINTMENT_CANCEL: 'appointment.cancel',
  QUEUE_READ: 'queue.read',
  QUEUE_MANAGE: 'queue.manage',
  SESSION_READ: 'session.read',
  SESSION_READ_OWN: 'session.read.own',
  SESSION_MANAGE: 'session.manage',
  SESSION_NOTES: 'session.notes',
  // money
  PACKAGE_READ: 'package.read',
  PACKAGE_MANAGE: 'package.manage',
  PACKAGE_SELL: 'package.sell',
  PACKAGE_REDEEM: 'package.redeem',
  MEMBERSHIP_READ: 'membership.read',
  MEMBERSHIP_MANAGE: 'membership.manage',
  MEMBERSHIP_SELL: 'membership.sell',
  POS_USE: 'pos.use',
  INVOICE_READ: 'invoice.read',
  INVOICE_CREATE: 'invoice.create',
  INVOICE_VOID: 'invoice.void',
  PAYMENT_READ: 'payment.read',
  PAYMENT_CREATE: 'payment.create',
  PAYMENT_REFUND: 'payment.refund',
  OFFER_READ: 'offer.read',
  OFFER_MANAGE: 'offer.manage',
  DISCOUNT_APPLY: 'discount.apply',
  LEDGER_READ: 'ledger.read',
  COMMISSION_READ: 'commission.read',
  COMMISSION_MANAGE: 'commission.manage',
  // management
  INVENTORY_READ: 'inventory.read',
  INVENTORY_PURCHASE: 'inventory.purchase',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',
  INVENTORY_TRANSFER_APPROVE: 'inventory.transfer.approve',
  PRODUCT_MANAGE: 'product.manage',
  EXPENSE_READ: 'expense.read',
  EXPENSE_MANAGE: 'expense.manage',
  REPORTS_READ: 'reports.read',
  REPORTS_FINANCIAL: 'reports.financial',
  REPORTS_EXPORT: 'reports.export',
  ANALYTICS_READ: 'analytics.read',
  HQ_DASHBOARD: 'hq.dashboard',
  // growth
  FEEDBACK_READ: 'feedback.read',
  FEEDBACK_MANAGE: 'feedback.manage',
  NOTIFICATION_MANAGE: 'notification.manage',
  CAMPAIGN_READ: 'campaign.read',
  CAMPAIGN_MANAGE: 'campaign.manage',
  RETENTION_READ: 'retention.read',
  // platform-ish, tenant side
  FRANCHISE_READ: 'franchise.read',
  FRANCHISE_MANAGE: 'franchise.manage',
  SUBSCRIPTION_MANAGE: 'subscription.manage',
  SUPPORT_USE: 'support.use',
  API_KEY_MANAGE: 'apikey.manage',
  BRANDING_MANAGE: 'branding.manage',
  AI_ASSISTANT_USE: 'ai.assistant.use',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

/** Permissions that can be granted to public API keys (the endpoints marked API-key allowed). */
export const API_KEY_SCOPES: { scope: Permission; label: string }[] = [
  { scope: PERMISSIONS.BRANCH_READ, label: 'Read branches' },
  { scope: PERMISSIONS.SERVICE_READ, label: 'Read services' },
  { scope: PERMISSIONS.THERAPIST_READ, label: 'Read therapists' },
  { scope: PERMISSIONS.CUSTOMER_READ, label: 'Read customers' },
  { scope: PERMISSIONS.CUSTOMER_CREATE, label: 'Create customers' },
  { scope: PERMISSIONS.APPOINTMENT_READ, label: 'Read appointments and availability' },
  { scope: PERMISSIONS.APPOINTMENT_CREATE, label: 'Book appointments' },
];

const P = PERMISSIONS;

const RECEPTION: Permission[] = [
  P.TENANT_READ,
  P.BRANCH_READ,
  P.SERVICE_READ,
  P.THERAPIST_READ,
  P.CUSTOMER_READ,
  P.CUSTOMER_CREATE,
  P.CUSTOMER_UPDATE,
  P.CUSTOMER_CONTACT_VIEW,
  P.APPOINTMENT_READ,
  P.APPOINTMENT_CREATE,
  P.APPOINTMENT_UPDATE,
  P.APPOINTMENT_CANCEL,
  P.QUEUE_READ,
  P.QUEUE_MANAGE,
  P.SESSION_READ,
  P.SESSION_MANAGE,
  P.PACKAGE_READ,
  P.PACKAGE_SELL,
  P.PACKAGE_REDEEM,
  P.MEMBERSHIP_READ,
  P.MEMBERSHIP_SELL,
  P.POS_USE,
  P.INVOICE_READ,
  P.INVOICE_CREATE,
  P.PAYMENT_READ,
  P.PAYMENT_CREATE,
  P.OFFER_READ,
  P.FEEDBACK_READ,
  P.INVENTORY_READ,
];

const BRANCH_MANAGER: Permission[] = [
  ...RECEPTION,
  P.USER_READ,
  P.ROLE_READ,
  P.SERVICE_MANAGE,
  P.THERAPIST_MANAGE,
  P.CUSTOMER_DELETE,
  P.SESSION_NOTES,
  P.INVOICE_VOID,
  P.PAYMENT_REFUND,
  P.DISCOUNT_APPLY,
  P.COMMISSION_READ,
  P.INVENTORY_PURCHASE,
  P.INVENTORY_ADJUST,
  P.INVENTORY_TRANSFER,
  P.EXPENSE_READ,
  P.EXPENSE_MANAGE,
  P.REPORTS_READ,
  P.REPORTS_FINANCIAL,
  P.REPORTS_EXPORT,
  P.ANALYTICS_READ,
  P.FEEDBACK_MANAGE,
  P.CAMPAIGN_READ,
  P.RETENTION_READ,
  P.SUPPORT_USE,
];

export const ROLE_TEMPLATES: Record<SystemRole, { name: string; description: string; permissions: Permission[] }> = {
  OWNER: { name: 'Owner', description: 'Full access to the entire business', permissions: ALL_PERMISSIONS },
  HQ_ADMIN: {
    name: 'HQ Admin',
    description: 'Manages multiple branches from HQ',
    permissions: ALL_PERMISSIONS.filter((p) => p !== P.SUBSCRIPTION_MANAGE && p !== P.API_KEY_MANAGE),
  },
  AREA_MANAGER: {
    name: 'Area Manager',
    description: 'Manages assigned branches',
    permissions: [...BRANCH_MANAGER, P.HQ_DASHBOARD, P.INVENTORY_TRANSFER_APPROVE],
  },
  BRANCH_MANAGER: { name: 'Branch Manager', description: 'Manages one branch', permissions: BRANCH_MANAGER },
  RECEPTIONIST: { name: 'Receptionist', description: 'Front desk operations', permissions: RECEPTION },
  THERAPIST: {
    name: 'Therapist',
    description: 'Delivers sessions',
    permissions: [P.TENANT_READ, P.SERVICE_READ, P.SESSION_READ_OWN, P.SESSION_MANAGE, P.SESSION_NOTES, P.CUSTOMER_READ, P.QUEUE_READ],
  },
  ACCOUNTANT: {
    name: 'Accountant',
    description: 'Payments, expenses, reports and reconciliation',
    permissions: [
      P.TENANT_READ,
      P.BRANCH_READ,
      P.INVOICE_READ,
      P.PAYMENT_READ,
      P.PAYMENT_CREATE,
      P.PAYMENT_REFUND,
      P.EXPENSE_READ,
      P.EXPENSE_MANAGE,
      P.REPORTS_READ,
      P.REPORTS_FINANCIAL,
      P.REPORTS_EXPORT,
      P.LEDGER_READ,
      P.COMMISSION_READ,
      P.COMMISSION_MANAGE,
    ],
  },
  INVENTORY_MANAGER: {
    name: 'Inventory Manager',
    description: 'Stock, purchases, transfers and adjustments',
    permissions: [
      P.TENANT_READ,
      P.BRANCH_READ,
      P.INVENTORY_READ,
      P.INVENTORY_PURCHASE,
      P.INVENTORY_ADJUST,
      P.INVENTORY_TRANSFER,
      P.PRODUCT_MANAGE,
      P.SERVICE_READ,
    ],
  },
};
